# Generated by Django 4.1.7 on 2023-09-02 07:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("web2androidapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="CreateApp", new_name="AppDetails",),
    ]
