# Generated by Django 4.1.7 on 2023-09-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web2androidapp", "0002_rename_createapp_appdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appdetails",
            name="app_image",
            field=models.ImageField(blank=True, null=True, upload_to="appimages"),
        ),
    ]
