# Generated by Django 4.1.7 on 2023-09-02 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("web2androidapp", "0003_alter_appdetails_app_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="appdetails",
            name="is_upload",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Likes",
            fields=[
                (
                    "basicinfo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web2androidapp.basicinfo",
                    ),
                ),
                ("total", models.IntegerField(default=0)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web2androidapp.appdetails",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("web2androidapp.basicinfo",),
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "basicinfo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web2androidapp.basicinfo",
                    ),
                ),
                ("content", models.CharField(max_length=100000)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web2androidapp.appdetails",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("web2androidapp.basicinfo",),
        ),
    ]
