# Generated by Django 4.1.7 on 2023-09-02 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web2androidapp", "0005_reviews"),
    ]

    operations = [
        migrations.RemoveField(model_name="likes", name="total",),
    ]
