# Generated by Django 4.1.7 on 2023-09-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web2androidapp", "0006_remove_likes_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="appdetails",
            name="total_downloads",
            field=models.IntegerField(default=0),
        ),
    ]
