# Generated by Django 4.1.7 on 2023-09-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web2androidapp", "0007_appdetails_total_downloads"),
    ]

    operations = [
        migrations.AddField(
            model_name="appdetails",
            name="about",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
