# Generated by Django 4.1.7 on 2023-09-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web2androidapp", "0010_userbasicinfo_about_userbasicinfo_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbasicinfo",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
