# Generated by Django 4.1.7 on 2023-09-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web2androidapp", "0011_userbasicinfo_website"),
    ]

    operations = [
        migrations.DeleteModel(name="Reviews",),
    ]
