# Generated by Django 4.1.7 on 2023-09-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web2androidapp", "0013_userbasicinfo_convert_limit_userbasicinfo_is_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbasicinfo",
            name="convert_limit",
            field=models.IntegerField(default=6),
        ),
    ]
